### ISSUE TITLE
Add Space between Home and App on Home Page

### ISSUE THREAD

**Issue by rayxke** [asheeeshh/waifus-for-programmers#16]
Maybe add some space between "Home" and "App" on the front page? I kept clicking what I thought was "HomeApp" wondering why the app wasn't opening.
![Image 10-18-22 at 1 55 AM](https://user-images.githubusercontent.com/8340687/196250022-64e69e13-dc46-4e49-a13c-8569b0f8d6e6.jpg)

**Comment by rayxke** [comment]
Added #17 to make a slight change for this.

![Image 10-18-22 at 2 23 AM](https://user-images.githubusercontent.com/8340687/196254198-8b2dd2d5-b503-4fd9-be03-ae1a88fbc155.jpg)

**Comment by asrvd** [comment]
> Maybe add some space between "Home" and "App" on the front page? I kept clicking what I thought was "HomeApp" wondering why the app wasn't opening. ![Image 10-18-22 at 1 55 AM](https://user-images.githubusercontent.com/8340687/196250022-64e69e13-dc46-4e49-a13c-8569b0f8d6e6.jpg)

weird cus it's fine for me, what's your browser and OS?
![image](https://user-images.githubusercontent.com/68690233/196489680-55e9ff05-fd1a-4229-b6be-7f04ecb9cad8.png)

**Comment by rayxke** [comment]
Mac OS 11.2.3 Big Sur Safari

**Comment by asrvd** [comment]
I see, I'll deploy your PR as preview, please let me know if it fixed your issue cus it's a user-specific issue
