### ISSUE TITLE
need UrlEncode in api

### ISSUE THREAD

**Issue by memorydream** [asheeeshh/waifus-for-programmers#2]
current
![image](https://user-images.githubusercontent.com/34763046/157128813-6feafd52-ddc8-43d7-a3ea-52c48f23e88e.png)

it is C not C#

**Comment by asrvd** [comment]
Thanks for creating the issue!
It's fixed now.
![image](https://user-images.githubusercontent.com/68690233/157164181-70e9f8c0-490e-4576-8255-9ffa26a0468b.png)

Closing the issue.
