### ISSUE TITLE
Discord Link doesn't work

### ISSUE THREAD

**Issue by TheRealDust** [asheeeshh/waifus-for-programmers#4]
The discord link on the web page seems to link to an individual discord account rather than a server. If the user's account is not already friended to the linked account the page simply redirects to the discord home page.

Suggested fix: Create/Link a discord server and set the discord icon on the web page to invite the user to it.

**Comment by asrvd** [comment]
Will fix it asap, thank you!

**Comment by asrvd** [comment]
1e371ff20c6202a32806167638550ad7d67daaac, fixed.
